CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER(20) PRIMARY KEY,
    NAME VARCHAR2(40) NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE NOT NULL,
    MOBILE_NUMBER NUMBER(10) UNIQUE NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL
);
DESC CUSTOMER;
CREATE TABLE RESTAURANT(
    RESTAURANT_ID NUMBER(20) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(100) NOT NULL,
    CONTACT_NUMBER NUMBER(10) UNIQUE,
    RATING NUMBER(1) CHECK (RATING IN (1,2,3,4,5))
);
DESC RESTAURANT;
CREATE TABLE FOOD_ITEM(
    ITEM_ID NUMBER(20) PRIMARY KEY,
    RESTAURANT_ID NUMBER(20) NOT NULL,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER(8,2) NOT NULL,

    CONSTRAINT FK_RESTAURANT_FOOD_ITEM
    FOREIGN KEY (RESTAURANT_ID)
    REFERENCES RESTAURANT(RESTAURANT_ID)
);
DESC FOOD_ITEM;
CREATE TABLE ORDERS(
    ORDER_ID NUMBER(20) PRIMARY KEY,
    CUSTOMER_ID NUMBER(20) NOT NULL,
    RESTAURANT_ID NUMBER(20) NOT NULL,
    ORDER_DATE DATE DEFAULT SYSDATE,
    ORDER_STATUS VARCHAR2(30),

    CONSTRAINT FK_CUSTOMER_ORDER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_RESTAURANT_ORDER
    FOREIGN KEY (RESTAURANT_ID)
    REFERENCES RESTAURANT(RESTAURANT_ID)
);
DESC ORDERS;
CREATE TABLE ORDER_ITEMS(
    ORDER_ITEM_ID NUMBER(20) PRIMARY KEY,
    ORDER_ID NUMBER(20) NOT NULL,
    ITEM_ID NUMBER(20) NOT NULL,
    QUANTITY NUMBER(5) NOT NULL,
    PRICE NUMBER(8,2) NOT NULL,

    CONSTRAINT FK_ORDER_ITEMS_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT FK_ORDER_ITEMS_FOOD
    FOREIGN KEY (ITEM_ID)
    REFERENCES FOOD_ITEM(ITEM_ID)
);
DESC ORDER_ITEMS;
CREATE TABLE DELIVERY_PERSON(
    DELIVERY_PERSON_ID NUMBER(20) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    MOBILE_NUMBER NUMBER(10) UNIQUE NOT NULL,
    VEHICLE_NUMBER VARCHAR2(20) UNIQUE,
    STATUS VARCHAR2(30)
);
DESC DELIVERY_PERSON;
CREATE TABLE DELIVERY(
    DELIVERY_ID NUMBER(20) PRIMARY KEY,
    ORDER_ID NUMBER(20) NOT NULL,
    DELIVERY_PERSON_ID NUMBER(20) NOT NULL,
    DELIVERY_STATUS VARCHAR2(30),
    DELIVERY_DATE DATE,

    CONSTRAINT FK_DELIVERY_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT FK_DELIVERY_PERSON
    FOREIGN KEY (DELIVERY_PERSON_ID)
    REFERENCES DELIVERY_PERSON(DELIVERY_PERSON_ID)
);
DESC DELIVERY;
CREATE TABLE PAYMENT(
    PAYMENT_ID NUMBER(20) PRIMARY KEY,
    ORDER_ID NUMBER(20) NOT NULL,
    PAYMENT_METHOD VARCHAR2(20)
        CHECK (PAYMENT_METHOD IN ('ONLINE','OFFLINE')),
    PAYMENT_STATUS VARCHAR2(20)
        CHECK (PAYMENT_STATUS IN ('DONE','NOT DONE')),
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_DATE DATE,

    CONSTRAINT FK_PAYMENT_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS(ORDER_ID)
);
DESC PAYMENT;

INSERT ALL
    INTO CUSTOMER (CUSTOMER_ID, NAME, EMAIL, MOBILE_NUMBER, ADDRESS)
    VALUES (1, 'Ravi Kumar', 'ravi@gmail.com', 9876543210, 'Vijayawada')

    INTO CUSTOMER (CUSTOMER_ID, NAME, EMAIL, MOBILE_NUMBER, ADDRESS)
    VALUES (2, 'Priya Sharma', 'priya@gmail.com', 9876543211, 'Guntur')

    INTO CUSTOMER (CUSTOMER_ID, NAME, EMAIL, MOBILE_NUMBER, ADDRESS)
    VALUES (3, 'Arjun', 'arjun@gmail.com', 9876543212, 'Hyderabad')

    INTO CUSTOMER (CUSTOMER_ID, NAME, EMAIL, MOBILE_NUMBER, ADDRESS)
    VALUES (4, 'Sneha Rao', 'sneha@gmail.com', 9876543213, 'Visakhapatnam')

    INTO CUSTOMER (CUSTOMER_ID, NAME, EMAIL, MOBILE_NUMBER, ADDRESS)
    VALUES (5, 'Kiran Kumar', 'kiran@gmail.com', 9876543214, 'Rajahmundry')
SELECT * FROM dual;



INSERT ALL
    INTO RESTAURANT (RESTAURANT_ID, NAME, LOCATION, CONTACT_NUMBER, RATING)
    VALUES (101, 'Subbayya gari hotel', 'Kakinada', 9123456780, 5)

    INTO RESTAURANT (RESTAURANT_ID, NAME, LOCATION, CONTACT_NUMBER, RATING)
    VALUES (102, 'Pizza Hub', 'Guntur', 9123456781, 4)

    INTO RESTAURANT (RESTAURANT_ID, NAME, LOCATION, CONTACT_NUMBER, RATING)
    VALUES (103, 'Spice Kitchen', 'Hyderabad', 9123456782, 5)

    INTO RESTAURANT (RESTAURANT_ID, NAME, LOCATION, CONTACT_NUMBER, RATING)
    VALUES (104, 'Food Corner', 'Visakhapatnam', 9123456783, 3)

    INTO RESTAURANT (RESTAURANT_ID, NAME, LOCATION, CONTACT_NUMBER, RATING)
    VALUES (105, 'Tasty Bites', 'Rajahmundry', 9123456784, 4)
SELECT * FROM dual;



INSERT ALL
    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (1, 101, 'Chicken Biryani', 250)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (2, 101, 'Mutton Biryani', 320)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (3, 101, 'Paneer Biryani', 220)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (4, 102, 'Veg Pizza', 250)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (5, 102, 'Chicken Pizza', 350)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (6, 103, 'Chicken Noodles', 200)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (7, 103, 'Paneer Curry', 180)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (8, 104, 'Burger', 150)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (9, 105, 'Fried Rice', 180)

    INTO FOOD_ITEM (ITEM_ID, RESTAURANT_ID, ITEM_NAME, PRICE)
    VALUES (10, 105, 'Manchurian', 160)
SELECT * FROM dual;
 


INSERT ALL
    INTO ORDERS (ORDER_ID, CUSTOMER_ID, RESTAURANT_ID, ORDER_DATE, ORDER_STATUS)
    VALUES (1001, 1, 101, SYSDATE, 'DELIVERED')

    INTO ORDERS (ORDER_ID, CUSTOMER_ID, RESTAURANT_ID, ORDER_DATE, ORDER_STATUS)
    VALUES (1002, 2, 102, SYSDATE, 'OUT FOR DELIVERY')

    INTO ORDERS (ORDER_ID, CUSTOMER_ID, RESTAURANT_ID, ORDER_DATE, ORDER_STATUS)
    VALUES (1003, 3, 103, SYSDATE, 'PREPARING')

    INTO ORDERS (ORDER_ID, CUSTOMER_ID, RESTAURANT_ID, ORDER_DATE, ORDER_STATUS)
    VALUES (1004, 1, 105, SYSDATE, 'DELIVERED')

    INTO ORDERS (ORDER_ID, CUSTOMER_ID, RESTAURANT_ID, ORDER_DATE, ORDER_STATUS)
    VALUES (1005, 4, 104, SYSDATE, 'PLACED')
SELECT * FROM dual;




INSERT ALL
    INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, ITEM_ID, QUANTITY, PRICE)
    VALUES (1, 1001, 1, 2, 250)

    INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, ITEM_ID, QUANTITY, PRICE)
    VALUES (2, 1001, 3, 1, 220)

    INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, ITEM_ID, QUANTITY, PRICE)
    VALUES (3, 1002, 5, 1, 350)

    INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, ITEM_ID, QUANTITY, PRICE)
    VALUES (4, 1002, 4, 2, 250)

    INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, ITEM_ID, QUANTITY, PRICE)
    VALUES (5, 1003, 6, 1, 200)

    INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, ITEM_ID, QUANTITY, PRICE)
    VALUES (6, 1004, 9, 2, 180)

    INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, ITEM_ID, QUANTITY, PRICE)
    VALUES (7, 1004, 10, 1, 160)

    INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, ITEM_ID, QUANTITY, PRICE)
    VALUES (8, 1005, 8, 2, 150)
SELECT * FROM dual;



INSERT ALL
    INTO DELIVERY_PERSON
    (DELIVERY_PERSON_ID, NAME, MOBILE_NUMBER, VEHICLE_NUMBER, STATUS)
    VALUES (501, 'Suresh', 9988776655, 'AP05AB1234', 'AVAILABLE')

    INTO DELIVERY_PERSON
    (DELIVERY_PERSON_ID, NAME, MOBILE_NUMBER, VEHICLE_NUMBER, STATUS)
    VALUES (502, 'Ramesh', 9988776656, 'AP07CD5678', 'BUSY')

    INTO DELIVERY_PERSON
    (DELIVERY_PERSON_ID, NAME, MOBILE_NUMBER, VEHICLE_NUMBER, STATUS)
    VALUES (503, 'Vijay', 9988776657, 'TS09EF9012', 'AVAILABLE')

    INTO DELIVERY_PERSON
    (DELIVERY_PERSON_ID, NAME, MOBILE_NUMBER, VEHICLE_NUMBER, STATUS)
    VALUES (504, 'Mahesh', 9988776658, 'AP16GH3456', 'BUSY')
SELECT * FROM dual;




INSERT ALL
    INTO DELIVERY
    (DELIVERY_ID, ORDER_ID, DELIVERY_PERSON_ID, DELIVERY_STATUS, DELIVERY_DATE)
    VALUES (701, 1001, 501, 'DELIVERED', SYSDATE)

    INTO DELIVERY
    (DELIVERY_ID, ORDER_ID, DELIVERY_PERSON_ID, DELIVERY_STATUS, DELIVERY_DATE)
    VALUES (702, 1002, 502, 'OUT FOR DELIVERY', SYSDATE)

    INTO DELIVERY
    (DELIVERY_ID, ORDER_ID, DELIVERY_PERSON_ID, DELIVERY_STATUS, DELIVERY_DATE)
    VALUES (703, 1003, 503, 'ASSIGNED', SYSDATE)

    INTO DELIVERY
    (DELIVERY_ID, ORDER_ID, DELIVERY_PERSON_ID, DELIVERY_STATUS, DELIVERY_DATE)
    VALUES (704, 1004, 504, 'DELIVERED', SYSDATE)
SELECT * FROM dual;



INSERT ALL
    INTO PAYMENT
    (PAYMENT_ID, ORDER_ID, PAYMENT_METHOD, PAYMENT_STATUS, TOTAL_AMOUNT, PAYMENT_DATE)
    VALUES (801, 1001, 'ONLINE', 'DONE', 720, SYSDATE)

    INTO PAYMENT
    (PAYMENT_ID, ORDER_ID, PAYMENT_METHOD, PAYMENT_STATUS, TOTAL_AMOUNT, PAYMENT_DATE)
    VALUES (802, 1002, 'ONLINE', 'DONE', 850, SYSDATE)

    INTO PAYMENT
    (PAYMENT_ID, ORDER_ID, PAYMENT_METHOD, PAYMENT_STATUS, TOTAL_AMOUNT, PAYMENT_DATE)
    VALUES (803, 1003, 'OFFLINE', 'NOT DONE', 200, SYSDATE)

    INTO PAYMENT
    (PAYMENT_ID, ORDER_ID, PAYMENT_METHOD, PAYMENT_STATUS, TOTAL_AMOUNT, PAYMENT_DATE)
    VALUES (804, 1004, 'ONLINE', 'DONE', 520, SYSDATE)

    INTO PAYMENT
    (PAYMENT_ID, ORDER_ID, PAYMENT_METHOD, PAYMENT_STATUS, TOTAL_AMOUNT, PAYMENT_DATE)
    VALUES (805, 1005, 'OFFLINE', 'NOT DONE', 300, SYSDATE)
SELECT * FROM dual;

COMMIT;

SELECT * FROM CUSTOMER;
SELECT * FROM RESTAURANT;
SELECT * FROM FOOD_ITEM;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM DELIVERY_PERSON;
SELECT * FROM DELIVERY;
SELECT * FROM PAYMENT;


